import "@/app/globals.css";
import { signOutAction } from "../actions";
import { APPLICATION_NAME } from "@/config";

export const metadata = {
  title: "Ship it quick ⚡️",
  description: "Generated by Next.js",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <div className="navbar bg-base-100">
        <div className="flex-1">
          <a className="btn btn-ghost text-xl">{APPLICATION_NAME}</a>
        </div>
        <div className="flex-none">
          <form>
            <button formAction={signOutAction} className="btn">
              Sign out
            </button>
          </form>
        </div>
      </div>
      <main>{children}</main>
    </>
  );
}
